org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.250
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=verox_rpg_prog
mod_name=Verox' RPG Progression
mod_license=All Rights Reserved
mod_version=1.21.1-0.0.7
mod_group_id=net.veroxuniverse
mod_authors=VeroxUniverse
mod_description=A world difficulty and progression mod, inspired by games like Terraria.

jei_version=19.5.0.44
irons_spells_version=1.21.1-3.16.3
geckolib_version=1.21.1:4.8.3
caelus_version=7.0.0+1.21
player_animator_version=2.0.4+1.21.1